name: TechKata CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Build
        run: ./gradlew build

      - name: Test
        run: ./gradlew test
        
